apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:  
  index.html: |  
    <!doctype html>  
    <html>  
      <head>  
        <meta charset="utf-8">  
        <title>Golang</title>  
        <link rel="stylesheet" href="main.css">  
      </head>  
      <body>  
        <h1>Code.education Rocks!</h1>
      </body>  
    </html>  