apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-nginx
  template:
    metadata:
      labels:
        app: code-nginx
    spec:
      containers:
      - name: code-nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            cpu: "250m"
            memory: "200Mi"
        

        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-html
          readOnly: true
        
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html
          items:
            - key: index.html
              path: index.html