apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-mysql
spec: #spec do Deployment
  replicas: 1

  selector: #selector utilizado para criar o service
    matchLabels:
      app: code-mysql
      tier: db

  template: #referente ao POD
    metadata:
      labels:
        app: code-mysql
        tier: db #identificacao
    spec: # spec do POD
      containers:
      - image: mysql:5.7
        name: code-mysql
        args:
          - "--ignore-db-dir=lost+found"
        
        env: # set variaveis de ambiente
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-code
              key: password

        ports:
        - containerPort: 3306
        
        volumeMounts: # monta o volume efetivamente
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      
      volumes: #definicao do volume
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim-code
        
